# fly.toml app configuration file generated for backend-summer-glade-8183 on 2025-01-07T01:26:55-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-summer-glade-8183'
primary_region = 'sin'
console_command = '/code/manage.py shell'

[build]

[env]
  BACKEND_ORIGIN_URL = 'https://backend-summer-glade-8183.fly.dev'
  FRONTEND_ORIGIN_URL = 'https://lustrous-hummingbird-27308d.netlify.app'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
