# Generated by Django 4.2.15 on 2024-11-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedtranscription',
            name='audio_file',
            field=models.FileField(upload_to='audio_files/'),
        ),
        migrations.AlterField(
            model_name='savedtranscription',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='image_files/'),
        ),
        migrations.AlterField(
            model_name='savedtranscription',
            name='score_data',
            field=models.JSONField(),
        ),
    ]
