# Generated by Django 4.2.17 on 2024-12-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_savedtranscription_user_userfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedtranscription',
            name='score_data',
            field=models.TextField(),
        ),
    ]
