# Generated by Django 4.2.15 on 2024-11-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_alter_savedtranscription_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtranscription',
            name='saves',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
