# Generated by Django 4.2.15 on 2024-11-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0003_savedtranscription_saves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedtranscription',
            name='saves',
            field=models.IntegerField(default=0),
        ),
    ]
