# Generated by Django 4.2.17 on 2024-12-21 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transcription', '0005_remove_savedtranscription_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedtranscription',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='savedtranscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_transcriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
