# Generated by Django 4.2.17 on 2024-12-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0006_remove_savedtranscription_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtranscription',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
